version: "3"
services:
  pg:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=calendar
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  calendar:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    container_name: calendar
    depends_on:
      - pg
    ports:
      - 8080:8080
