version: "3"
services:
  pg:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=calendar
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3.13
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=calendar
      - RABBITMQ_DEFAULT_PASS=calendar
    ports:
      - 5672:5672
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  calendar:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    container_name: calendar
    depends_on:
      - pg
    ports:
      - 3000:3000
      - 50051:50051
