logger:
  level: INFO
  output: logs/development.log
storage:
  type: memory
db:
  host: 127.0.0.1
  port: 5432
  dbName: calendar_development
  user: calendar_development
  password: calendar_development
server:
  host: localhost
  port: '3000'
  readTimeout: 2s
  ReadHeaderTimeout: 2s
  writeTimeout: 2s
grpc:
  host: localhost
  port: '50051'
